fix(gitlab): allow unauthenticated users.get()
When using `users.get('someone')` with GitLab and no auth, the library throws:

```
InsufficientScopeError: Credentials lack the scope or permission for this request
```

It should be possible to fetch a user without auth, and the information is in fact there, so return
it instead of throwing.